### ISSUE TITLE
Generate From File

### ISSUE THREAD

**Issue by tsantos84** [jdesrosiers/silex-swagger-provider#11]
Is there a simple way to generate the UI from an `swagger.json` or `swagger.yml` file?

**Comment by jdesrosiers** [comment]
I'm no longer maintaining the this project.  You're better off asking somewhere else.  Swagger has changed since I've used it last.  I don't know how it works today, but I imagine this part hasn't changed.  There used to be a swagger-ui project that is a generic UI for Swagger defined API.  You point it at your swagger files and that's all it needs.  So, you don't actually generate a UI, you use a generic UI.  My guess is that project is still around in some form.  I suggest looking for that.
