### ISSUE TITLE
Silex 2.0 support

### ISSUE THREAD

**Issue by gregbiv** [jdesrosiers/silex-swagger-provider#8]
Hi! Any updates for supporting new version of silex?

**Comment by jdesrosiers** [comment]
I've been holding off on Silex 2.0 support until Silex 2.0 is officially released.  But, I suppose if there is demand for it, I can create a branch for that purpose.  I just won't merge and tag it until Silex 2.0 is officially released.

Pull Requests are welcome if you want to contribute, otherwise I should be able to get to it later this week.

**Comment by jdesrosiers** [comment]
Silex 2.0 support has been added in the `silex-2` branch.
